name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install environtment
        run: npm ci

      - name: Test and Build
        run: |
          npx nx test ma-core --ci --code-coverage
          npx nx test ma-ui-mantine --ci --code-coverage
          npx nx build ma-core
          npx nx build ma-ui-mantine

      - name: Setup GIT
        run: |
          git config --local --list
          git checkout main
          git config user.email "$GH_EMAIL"
          git config user.name "Imanuel Pundoko"
        env:
          GH_EMAIL: ${{secrets.GH_EMAIL}}

      - name: Bump version
        run: git reset --hard
        working-directory: ./dist/libs/ma-core
        run: npm version patch
        working-directory: ./dist/libs/ma-ui-mantine
        run: npm version patch

      # - name: npm publish
      #   run: |
      #     npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
      #     npm run trypublish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
